SYSLOG_HOST = "0.0.0.0"
SYSLOG_PORT = 12000
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB_NUMBER = 10
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
CACHE_TIMEOUT = 5
TOP_MOST_ACCESSED_URIS = 10

TELEGRAM_BOT_TOKEN = '864356139:gdfgdfhfdsNdsfhfgjmNk'
TELEGRAM_BOT_EXTERNAL_URL = 'https://example.com:8443'
TELEGRAM_BOT_USE_WEBHOOK = True
TELEGRAM_BOT_AUTH_CODE = 'EIsadsdgyFuC'

USE_FIRESTORE = False
